model: tf_efficientdet_d1
num_classes: 2
batch_size: 8
grad_accum_steps: 4
epochs: 100
workers: 4
pretrained: false
native_amp: true
pin_mem: true
opt: momentum
momentum: 0.9
weight_decay: 0.00004
lr: 0.01
sched: cosine
warmup_epochs: 5
cooldown_epochs: 0
model_ema: true
model_ema_decay: 0.9998
eval_metric: map
seed: 13
log_interval: 10
recovery_interval: 0
experiment: training
